hidden_layers_binary:
  - type: linear
    kwargs:
      in_features: 512
      out_features: 128
      bias: true
  - type: relu_activation
    kwargs:
      inplace: false
  - type: dropout
    kwargs:
      p: 0.5
      inplace: true

  - type: linear
    kwargs:
      in_features: 128
      out_features: 64
      bias: true
  - type: relu_activation
    kwargs:
      inplace: false
  - type: dropout
    kwargs:
      p: 0.5
      inplace: true

  - type: linear
    kwargs:
      in_features: 64
      out_features: 128
      bias: true
  - type: relu_activation
    kwargs:
      inplace: false
  - type: dropout
    kwargs:
      p: 0.5
      inplace: true

hidden_layers_multi:
  - type: linear
    kwargs:
      in_features: 512
      out_features: 256
      bias: true
  - type: relu_activation
    kwargs:
      inplace: false
  - type: dropout
    kwargs:
      p: 0.5
      inplace: true

  - type: linear
    kwargs:
      in_features: 256
      out_features: 128
      bias: true
  - type: relu_activation
    kwargs:
      inplace: false
  - type: dropout
    kwargs:
      p: 0.5
      inplace: true

  - type: linear
    kwargs:
      in_features: 128
      out_features: 256
      bias: true
  - type: relu_activation
    kwargs:
      inplace: false
  - type: dropout
    kwargs:
      p: 0.5
      inplace: true

attribute_classification_layers:
  - type: linear
    attribute: age
    activation: none
    kwargs:
      in_features: 256
      out_features: 4
      bias: true

  - type: linear
    attribute: backpack
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: bag
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: clothes
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: down
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: down_colours
    activation: none
    kwargs:
      in_features: 256
      out_features: 9
      bias: true

  - type: linear
    attribute: gender
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: hair
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: handbag
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: hat
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: up
    activation: sigmoid
    kwargs:
      in_features: 128
      out_features: 1
      bias: true

  - type: linear
    attribute: up_colours
    activation: none
    kwargs:
      in_features: 256
      out_features: 8
      bias: true

attributes_to_use:
  - age
  - down_colours
  - up_colours

dataloader:
  kwargs:
    batch_size: 2
    num_workers: 4

backbone:
  kwargs:
    backbone_name: resnet50
    pretrained: true
    trainable_layers: 0

backbone_output_to_use: 3

epochs: 10

optimizer:
  kwargs:
    lr: 0.005

scheduler:
  kwargs:
    milestones: 5
    gamma: 0.2
